### ISSUE TITLE
Generating local gold standard is broken

### ISSUE THREAD

**Issue by chummels** [trident-project/trident#132]
I'm trying to do some local testing before making some commits.  So I follow the documentation on generating a local gold standard: https://trident.readthedocs.io/en/latest/testing.html#generating-answer-tests

Unfortunately, it fails because it cannot seem to find a travis config file.  Since we're not even using travis anymore, I guess this file got removed but not the check for it?  I'm not sure how to proceed since we've had the big switch over to circle-ci.  Perhaps there is a different way that we're supposed to be generating the local gold standard now, but the docs are suggesting this method.  Suggestions, @brittonsmith ?

This run on yt-4.0 tip and trident master tip.  Here is the callback:

```
[cambot:~/src/trident/tests] chummels% python gold_standard_versions.py
Traceback (most recent call last):
  File "gold_standard_versions.py", line 36, in <module>
    get_gold_standard_version()
  File "gold_standard_versions.py", line 18, in get_gold_standard_version
    f = open(os.path.join(trident_path, '../.travis.yml'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chummels/src/trident/trident/../.travis.yml'
```

**Comment by chummels** [comment]
Fixed in PR #133
