### ISSUE TITLE
trident.verify fails in sph-viz branch

### ISSUE THREAD

**Issue by claytonstrawn** [trident-project/trident#77]
When I switch from the `master` branch to the `sph-viz` branch and reinstall via `pip install -e .` it seems to work ok and successfully `import`s but the function `trident.verify()` does not seem to work.

I tested that it was indeed `trident` and not `h5py` errors by checking out and reinstalling `master`, and it worked fine there, and came back to `sph-viz` and it was still broken. I'm not sure why this happened, it seems deep in the weeds of `h5py`. 

Full terminal output below.

```Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import trident
>>> trident.verify()

Creating single-cell dataset
----------------------------

yt : [INFO     ] 2019-02-15 15:21:52,691 Parameters: current_time              = 0.0
yt : [INFO     ] 2019-02-15 15:21:52,691 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2019-02-15 15:21:52,691 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2019-02-15 15:21:52,692 Parameters: domain_right_edge         = [3.08567758e+22 3.08567758e+22 3.08567758e+22]
yt : [INFO     ] 2019-02-15 15:21:52,692 Parameters: cosmological_simulation   = 0.0

Creating ray object through single-cell dataset
-----------------------------------------------

yt : [INFO     ] 2019-02-15 15:21:53,109 Getting segment at z = 0.0: [0. 0. 0.] unitary to [1. 1. 1.] unitary.
yt : [INFO     ] 2019-02-15 15:21:53,112 Getting subsegment: [0.0 unitary, 0.0 unitary, 0.0 unitary] to [0.9999999999999999 unitary, 0.9999999999999999 unitary, 0.9999999999999999 unitary].
/Users/claytonstrawn/yt/yt/units/yt_array.py:1394: RuntimeWarning: invalid value encountered in divide
  out=out, **kwargs)
yt : [INFO     ] 2019-02-15 15:21:53,138 Saving field data to yt dataset: /var/folders/r4/3zn5tyqj4sx0s4t35db7kspc0000gn/T/tmpUPnkwm/ray.h5.
yt : [INFO     ] 2019-02-15 15:21:53,370 Parameters: current_time              = 0.0 code_time
yt : [INFO     ] 2019-02-15 15:21:53,370 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2019-02-15 15:21:53,370 Parameters: domain_left_edge          = [0. 0. 0.] code_length
yt : [INFO     ] 2019-02-15 15:21:53,371 Parameters: domain_right_edge         = [3.08567758e+22 3.08567758e+22 3.08567758e+22] code_length
yt : [INFO     ] 2019-02-15 15:21:53,371 Parameters: cosmological_simulation   = 0.0

Create spectrum with Lyman alpha, Mg II, and O VI lines
-------------------------------------------------------

yt : [INFO     ] 2019-02-15 15:21:53,372 Setting instrument to COS
yt : [INFO     ] 2019-02-15 15:21:53,392 Allocating for 1.000e+00 particles (index particle type 'all')
yt : [INFO     ] 2019-02-15 15:21:53,407 Allocating for 1.000e+00 particles (index particle type 'all')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/claytonstrawn/trident/trident/config.py", line 247, in verify
    sg.make_spectrum(ray, lines=['Ly a', 'Mg II', 'O VI'])
  File "/Users/claytonstrawn/trident/trident/spectrum_generator.py", line 371, in make_spectrum
    if alias_field in ray.derived_field_list:
  File "/Users/claytonstrawn/yt/yt/data_objects/static_output.py", line 217, in ireq
    self.index
  File "/Users/claytonstrawn/yt/yt/data_objects/static_output.py", line 510, in index
    self, dataset_type=self.dataset_type)
  File "/Users/claytonstrawn/yt/yt/geometry/particle_geometry_handler.py", line 39, in __init__
    super(ParticleIndex, self).__init__(ds, dataset_type)
  File "/Users/claytonstrawn/yt/yt/geometry/geometry_handler.py", line 50, in __init__
    self._setup_geometry()
  File "/Users/claytonstrawn/yt/yt/geometry/particle_geometry_handler.py", line 50, in _setup_geometry
    self._initialize_particle_handler()
  File "/Users/claytonstrawn/yt/yt/geometry/particle_geometry_handler.py", line 104, in _initialize_particle_handler
    self._initialize_indices()
  File "/Users/claytonstrawn/yt/yt/geometry/particle_geometry_handler.py", line 134, in _initialize_indices
    self.io._initialize_index(data_file, self.regions)
  File "/Users/claytonstrawn/yt/yt/frontends/ytdata/io.py", line 238, in _initialize_index
    dx = f["grid"]["dx"][()].min()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/claytonstrawn/anaconda2/envs/myenv/lib/python2.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'dx' doesn't exist)"```

**Comment by claytonstrawn** [comment]
might be useful to note I also tried this on a `Linux` `posix` computer as well as my Mac, it did the same thing both times

**Comment by chummels** [comment]
Hi Clayton.  I think your issue is that you're not updating yt to the `yt-4.0` branch when you change trident to the `sph-viz` branch.  Trident's `sph-viz` branch is only meant to be used with yt's `yt-4.0` branch, otherwise it doesn't work.  I have tested locally on a mac and I get the behavior you're seeing when I leave yt on the `master` branch and move trident to the `sph-viz` branch.

So when you use normal trident (i.e., the `master` branch), you must pair it with the `master` branch of yt, and when you use the demeshened version of trident (i.e., `sph-viz` branch), you must use yt's `yt-4.0` branch.  I guess I should make this more clear in our documentation: https://nbviewer.jupyter.org/url/trident-project.org/notebooks/trident_demesh_install.ipynb .  But also, we're planning to simplify this with a stable release in the next couple of weeks and then only have one development branch that works with `yt-4.0`.

Can you confirm that you get things to work when you change to `yt-4.0`?

```
$ cd <yt directory>
$ git checkout yt-4.0
$ pip install -e .
$ cd <trident directory>
$ git checkout sph-viz
$ pip install -e .
$ cd <working directory>
$ python
>>> import trident
>>> trident.verify()
```

**Comment by chummels** [comment]
@claytonstrawn I assume that my suggestion addressed your problem.  Can you please let us know so I can close this issue?

**Comment by claytonstrawn** [comment]
@chummels Yep, that was the problem. Sorry for forgetting to reply to your last message! I can close this now.
